global:
  isLocalEnv: false
  containerRegistry:
    path: eu.gcr.io/kyma-project
  istio_webhook:
    dir:
    version: 1.0.0
  istio_kyma_patch:
<<<<<<< HEAD
    dir:
    version: 1.0.0
=======
    dir: develop/
    version: e0e414f1
>>>>>>> master
