#
# addon kiali
#
enabled: false 
replicaCount: 1
hub: docker.io/kiali
tag: v0.14
contextPath: /
nodeSelector: {}
ingress:
  enabled: false 
  ## Used to create an Ingress record.
  hosts:
    - kiali.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: kiali-tls
    #   hosts:
    #     - kiali.local

dashboard:
  secretName: kiali
  usernameKey: username
  passphraseKey: passphrase

credentials:
  username: admin

  # Override the automatically detected Grafana URL, useful when Grafana service has no ExternalIPs
  # grafanaURL:

  # Override the automatically detected Jaeger URL, useful when Jaeger service has no ExternalIPs
  # jaegerURL:
prometheusAddr: http://monitoring-prometheus.kyma-system:9090
